var env={};
env.ELASTIC_TRANSCODER_REGION = 'us-east-1';
env.ELASTIC_TRANSCODER_PIPELINE_ID = 'ELASTIC TRANSCODER PIPELINE ID';
env.SERVICE_ACCOUNT = 'YOUR SERVICE_ACCOUNT HERE';
env.DATABASE_URL = 'YOUR DATABASE_URL HERE';
module.exports = env;
