var env={};
env.ELASTIC_TRANSCODER_REGION = 'us-east-1';
env.ELASTIC_TRANSCODER_PIPELINE_ID = 'ELASTIC TRANSCODER PIPELINE ID';
env.FIREBASE_URL = 'YOUR FIREBASE URL HERE';
env.FIREBASE_SECRET = 'YOUR FIREBASE SECRET HERE';
module.exports = env;
